export const PostsActionTypes = {
  SET_POSTS: "SET_POSTS",
  FETCH_POSTS: "FETCH_POSTS",
  SET_LOADING_STATE: "SET_LOADING_STATE",
  FETCH_ADD_POST: "FETCH_ADD_POST",
  ADD_POST: "ADD_POST",
  SET_ADD_FORM_STATE: "SET_ADD_FORM_STATE",
};

export const LoadingState = {
  LOADED: "LOADED",
  LOADING: "LOADING",
  ERROR: "ERROR",
  NEVER: "NEVER",
};

export const AddFormState = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  NEVER: "NEVER",
};
